### ISSUE TITLE
Matlab compilation error

### ISSUE THREAD

**Issue by h1010302** [aviumtechnologies/ardupilot-sil-connector#1]
Greetings Dears, 
I tried to run make file but Matlab threw heaps of undefined references and an error as shown below:

> Building with 'MinGW64 Compiler (C++)'.
> Error using mex
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x34a):
> undefined reference to `__imp_WSAStartup'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x5c4):
> undefined reference to `__imp_WSACleanup'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x5e6):
> undefined reference to `__imp_WSACleanup'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x2c22):
> undefined reference to `__imp_ioctlsocket'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x2c8a):
> undefined reference to `__imp_WSAGetLastError'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x2d54):
> undefined reference to `__imp_WSAGetLastError'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x2dd2):
> undefined reference to `__imp_WSARecvFrom'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x2eb2):
> undefined reference to `__imp_select'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x33f4):
> undefined reference to `__imp_WSASendTo'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x34a4):
> undefined reference to `__imp_select'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x3bb7):
> undefined reference to `__imp_WSASend'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x3bc2):
> undefined reference to `__imp_WSAGetLastError'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x3e28):
> undefined reference to `__imp_WSASetLastError'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x3e52):
> undefined reference to `__imp_WSAStringToAddressA'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x3e69):
> undefined reference to `__imp_WSAGetLastError'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x3ec3):
> undefined reference to `__imp_htons'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x3f25):
> undefined reference to `__imp_setsockopt'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x3fe1):
> undefined reference to `__imp_bind'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x42f2):
> undefined reference to `__imp_htons'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x42ff):
> undefined reference to `__imp_ntohl'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x4307):
> undefined reference to `__imp_htonl'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x459a):
> undefined reference to `__imp_WSACleanup'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text+0x45cb):
> undefined reference to `__imp_WSAStartup'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code[_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code]+0x41):
> undefined reference to `__imp_closesocket'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code[_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code]+0x78):
> undefined reference to `__imp_WSAGetLastError'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code[_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code]+0xbf):
> undefined reference to `__imp_ioctlsocket'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code[_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code]+0x11f):
> undefined reference to `__imp_setsockopt'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code[_ZN4asio6detail10socket_ops5closeEyRhbRSt10error_code]+0x132):
> undefined reference to `__imp_WSAGetLastError'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail14select_reactor21deregister_descriptorEyRNS1_19per_descriptor_dataEb[_ZN4asio6detail14select_reactor21deregister_descriptorEyRNS1_19per_descriptor_dataEb]+0x2a4):
> undefined reference to `__imp_WSASend'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail14select_reactor21deregister_descriptorEyRNS1_19per_descriptor_dataEb[_ZN4asio6detail14select_reactor21deregister_descriptorEyRNS1_19per_descriptor_dataEb]+0x2af):
> undefined reference to `__imp_WSAGetLastError'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3udpEE8shutdownEv[_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3udpEE8shutdownEv]+0x3b8):
> undefined reference to `__imp_WSASend'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3udpEE8shutdownEv[_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3udpEE8shutdownEv]+0x3cd):
> undefined reference to `__imp_WSAGetLastError'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3udpEE4openERNS4_19implementation_typeERKS3_RSt10error_code[_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3udpEE4openERNS4_19implementation_typeERKS3_RSt10error_code]+0xc6):
> undefined reference to `__imp_WSASocketW'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3udpEE4openERNS4_19implementation_typeERKS3_RSt10error_code[_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3udpEE4openERNS4_19implementation_typeERKS3_RSt10error_code]+0x1ba):
> undefined reference to `__imp_WSAGetLastError'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3udpEE4openERNS4_19implementation_typeERKS3_RSt10error_code[_ZN4asio6detail23win_iocp_socket_serviceINS_2ip3udpEE4openERNS4_19implementation_typeERKS3_RSt10error_code]+0x1f3):
> undefined reference to `__imp_setsockopt'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail14io_object_implINS0_23win_iocp_socket_serviceINS_2ip3udpEEENS_15any_io_executorEED1Ev[_ZN4asio6detail14io_object_implINS0_23win_iocp_socket_serviceINS_2ip3udpEEENS_15any_io_executorEED1Ev]+0x3a8):
> undefined reference to `__imp_WSASend'
> C:\Users\hisha\AppData\Local\Temp\mex_75064125702886_19368\ardupilot_sil_connector.obj:ardupilot_sil_connector.cpp:(.text$_ZN4asio6detail14io_object_implINS0_23win_iocp_socket_serviceINS_2ip3udpEEENS_15any_io_executorEED1Ev[_ZN4asio6detail14io_object_implINS0_23win_iocp_socket_serviceINS_2ip3udpEEENS_15any_io_executorEED1Ev]+0x3b3):
> undefined reference to `__imp_WSAGetLastError'
> collect2.exe: error: ld returned 1 exit status
> 
> 
> Error in make (line 4)
> mex -I./includes/includes ardupilot_sil_connector.cpp

I am using Matlab2023a and tried 2021a both on windows 10. Could you help me please resolve this issue?

Regards,
Hisham

**Comment by h1010302** [comment]
Resolved I just added the path to WS2_32.lib to mex command inside make file:

> mex -I./includes -lWS2_32 -L"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64" ardupilot_sil_connector.cpp

Regards,
Hisham

**Comment by aogrcs** [comment]
Yes, It does work, how do you find this @h1010302 h1010302?
Thanks
